export const ROUTES = {
  HOME_PAGE: "/home",
  PRODUCT_PAGE: "/products",
  ABOUT_US_PAGE: "/about",
  DETAIL_PRODUCT_PAGE: "/products/:productId",
  BLOG_PAGE: "/blog",
  LOGIN_PAGE: "/login",
  REGISTER_PAGE: "/register",
  CART_PAGE: "/cart",
  USER_PAGE: "/user",
  USER_PROFILE_PAGE: "/user/profile",
  USER_CHANGE_PASSWORD_PAGE: "/user/password",
  USER_PURCHASE_HISTORY_PAGE: "/user/purchase-history",
  ORDER_PAGE: "/order",
  CHECK_OUT_PAGE: "/checkout",
};
